
apiVersion: v1
kind: ConfigMap
metadata:
  name: labeler
  namespace: kube-system
data:
  config.yaml: |-
    ---
    namespace: labeler.io
    region: us-east-2
    provider: aws
    excludes:
      Name: true
      aws:autoscaling:groupName: true
      kubernetes.io/cluster/jpw : true
